[package]
name = "findrs"
version = "0.1.0"
edition = "2021"

[dependencies]
ansi_term = "0.12"
clap = "3.0.0-beta.5"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "my_benchmark"
harness = false